### ISSUE TITLE
电脑端的 请问CK文件填在哪里?

### ISSUE THREAD

**Issue by cmazfuture** [2079898548/jd_lzsnmb#10]
电脑端的 请问CK文件填在哪里? ,第一个箭头我填进去运行有问题,第二个箭头,我把CK删了,把真正的CK填进去也是报
![QQ图片20211107223027](https://user-images.githubusercontent.com/71751136/140649443-4c27b596-85f7-405e-a9ee-943a84f8c20e.png)
错

**Comment by cmazfuture** [comment]
请问网页版的CK格式是啥,手机端的是pt_key=XXXXXpt_pin=XXXX;

**Comment by Ocyss** [comment]
thor？你看看差不多的。pin照样，就是key换thor。。


位置那个开头那个ck里面

**Comment by boopzk22** [comment]
> thor？你看看差不多的。pin照样，就是key换thor。。 位置那个开头那个ck里面

待评价订单 9----待晒单 45----待追评 213----服务评价 2----已评价 0----
1.开始普通评价
当前共有9个评价。
Traceback (most recent call last):
  File "/Users/ccc/Desktop/jd/jd_lzsnmb-jd/1.py", line 325, in <module>
    main()
  File "/Users/ccc/Desktop/jd/jd_lzsnmb-jd/1.py", line 307, in main
    N = ordinary(N)
  File "/Users/ccc/Desktop/jd/jd_lzsnmb-jd/1.py", line 139, in ordinary
    oid = Order.xpath('tr[@class="tr-th"]/td/span[3]/a/text()')[0]
IndexError: list index out of range

**Comment by Ocyss** [comment]
。。。京东可能换规则了，过几天修复吧。md😂😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月8日(周一) 下午3:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiu-lzsnmb/jd_lzsnmb] 电脑端的 请问CK文件填在哪里? (Issue #10)




  
thor？你看看差不多的。pin照样，就是key换thor。。 位置那个开头那个ck里面
  
待评价订单 9----待晒单 45----待追评 213----服务评价 2----已评价 0----
 1.开始普通评价
 当前共有9个评价。
 Traceback (most recent call last):
 File "/Users/ccc/Desktop/jd/jd_lzsnmb-jd/1.py", line 325, in 
 main()
 File "/Users/ccc/Desktop/jd/jd_lzsnmb-jd/1.py", line 307, in main
 N = ordinary(N)
 File "/Users/ccc/Desktop/jd/jd_lzsnmb-jd/1.py", line 139, in ordinary
 oid = ***@***.***="tr-th"]/td/span[3]/a/text()')[0]
 IndexError: list index out of range
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ocyss** [comment]
修复好了，试试

**Comment by Takea3** [comment]
> 修复好了，焕然一新

多个ck怎办？

**Comment by Ocyss** [comment]
凉拌



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月28日(周日) 下午2:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiu-lzsnmb/jd_lzsnmb] 电脑端的 请问CK文件填在哪里? (Issue #10)




  
修复好了，焕然一新
  
多个ck怎办？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
