### ISSUE TITLE
电脑端报错 IndexError

### ISSUE THREAD

**Issue by MichaelPan1026** [2079898548/jd_lzsnmb#12]
```
list index out of range
  File "F:\Users\i\OneDrive - sunsweets\Desktop\自动评价-电脑端.py", line 139, in ordinary
    oid = Order.xpath('tr[@class="tr-th"]/td/span[3]/a/text()')[0]
  File "F:\Users\i\OneDrive - sunsweets\Desktop\自动评价-电脑端.py", line 307, in main
    N = ordinary(N)
  File "F:\Users\i\OneDrive - sunsweets\Desktop\自动评价-电脑端.py", line 325, in <module>
    main()
```
console: 
```
开始京东批量评价！


待评价订单 6----待晒单 1----待追评 36----服务评价 12----已评价 0----
1.开始普通评价
当前共有6个评价。

```

**Comment by bjw211** [comment]
开始京东批量评价！


待评价订单 37----待晒单 4----待追评 59----服务评价 50----已评价 0----
1.开始普通评价
当前共有37个评价。
Traceback (most recent call last):
  File "jd_pj.py", line 325, in <module>
    main()
  File "jd_pj.py", line 307, in main
    N = ordinary(N)
  File "jd_pj.py", line 139, in ordinary
    oid = Order.xpath('tr[@class="tr-th"]/td/span[3]/a/text()')[0]
IndexError: list index out of range

相同的错，

**Comment by Ocyss** [comment]
知道，没空修












lzsnmb
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月17日(周三) 中午1:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [qiu-lzsnmb/jd_lzsnmb] 电脑端报错 IndexError (Issue #12)




 
开始京东批量评价！
 
待评价订单 37----待晒单 4----待追评 59----服务评价 50----已评价 0----
 1.开始普通评价
 当前共有37个评价。
 Traceback (most recent call last):
 File "jd_pj.py", line 325, in 
 main()
 File "jd_pj.py", line 307, in main
 N = ordinary(N)
 File "jd_pj.py", line 139, in ordinary
 oid = ***@***.***="tr-th"]/td/span[3]/a/text()')[0]
 IndexError: list index out of range
 
相同的错，
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ocyss** [comment]
修复好了，试试

**Comment by MichaelPan1026** [comment]
> 修复好了，试试

好了，可以用了，非常感谢！
