### ISSUE TITLE
电脑版报错

### ISSUE THREAD

**Issue by free-diy** [2079898548/jd_lzsnmb#19]
Traceback (most recent call last):
  File "D:\自动评价\自动评价-电脑端.py", line 330, in <module>
    main()
  File "D:\自动评价\自动评价-电脑端.py", line 325, in main
    main()
  File "D:\自动评价\自动评价-电脑端.py", line 325, in main
    main()
  File "D:\自动评价\自动评价-电脑端.py", line 325, in main
    main()
  [Previous line repeated 16 more times]
  File "D:\自动评价\自动评价-电脑端.py", line 309, in main
    if N['待晒单'] != 0:
KeyError: '待晒单'
[Finished in 186.6s]

**Comment by Ocyss** [comment]
啊这，不应该的吧，这个我也没遇到过。换下ck在多试试，还一样我在看看
