### ISSUE TITLE
电脑端报错

### ISSUE THREAD

**Issue by googooog** [2079898548/jd_lzsnmb#24]
开始京东批量评价！

Traceback (most recent call last):
  File "/Users/sy/jd_AutoComment/1.py", line 332, in <module>
    main()
  File "/Users/sy/jd_AutoComment/1.py", line 300, in main
    N = No()
  File "/Users/sy/jd_AutoComment/1.py", line 291, in No
    N = all_evaluate()
  File "/Users/sy/jd_AutoComment/1.py", line 110, in all_evaluate
    req = requests.get(url, headers=headers)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1326, in _send_request
    self.putheader(hdr, value)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1258, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 0: ordinal not in range(256)

**Comment by Ocyss** [comment]
好像是编码什么问题。。。。这你看看，应该和系统有关












lzsnmb
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月20日(周日) 晚上10:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiu-lzsnmb/jd_lzsnmb] 电脑端报错 (Issue #24)




 
开始京东批量评价！
 
Traceback (most recent call last):
 File "/Users/sy/jd_AutoComment/1.py", line 332, in 
 main()
 File "/Users/sy/jd_AutoComment/1.py", line 300, in main
 N = No()
 File "/Users/sy/jd_AutoComment/1.py", line 291, in No
 N = all_evaluate()
 File "/Users/sy/jd_AutoComment/1.py", line 110, in all_evaluate
 req = requests.get(url, headers=headers)
 File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 75, in get
 return request('get', url, params=params, **kwargs)
 File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 61, in request
 return session.request(method=method, url=url, **kwargs)
 File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
 resp = self.send(prep, **send_kwargs)
 File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
 r = adapter.send(request, **kwargs)
 File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
 resp = conn.urlopen(
 File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
 httplib_response = self._make_request(
 File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
 conn.request(method, url, **httplib_request_kw)
 File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
 super(HTTPConnection, self).request(method, url, body=body, headers=headers)
 File ***@***.***/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
 self._send_request(method, url, body, headers, encode_chunked)
 File ***@***.***/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1326, in _send_request
 self.putheader(hdr, value)
 File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader
 _HTTPConnection.putheader(self, header, *values)
 File ***@***.***/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1258, in putheader
 values[i] = one_value.encode('latin-1')
 UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 0: ordinal not in range(256)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dimlitter** [comment]
他跑错地方了...在我那儿提了issue又跑这来...我真无语了，这是cookie中存在非ASC二字符，是我那边改动导致的，跟您这边一点关系也没有...这些什么人呐，抱歉给您添麻烦了
