### ISSUE TITLE
通知好像有问题

### ISSUE THREAD

**Issue by ghost** [2079898548/jd_lzsnmb#8]
tg服务启动
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6998bf2fa0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1234567890:xxxxxxx/sendMessage?chat_id=1234567890&text=%E4%BA%AC%E4%B8%9C%E5%85%A8%E8%87%AA%E5%8A%A8%E8%AF%84%E4%BB%B7%0A%0A%E8%B4%A6%E5%8F%B71%5B%E9%85%92%E5%B7%B7joux%5D%0A%7B%27%E8%AF%84%E4%BB%B7%27%3A+0%2C+%27%E6%99%92%E5%8D%95%27%3A+0%2C+%27%E6%9C%8D%E5%8A%A1%E8%AF%84%E4%BB%B7%27%3A+1%7D%0A%0A&disable_web_page_preview=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6998bf2fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "raw_jd_Evaluation.py", line 513, in <module>
    start()
  File "raw_jd_Evaluation.py", line 509, in start
    send('京东全自动评价', msg)
  File "/ql/scripts/notify.py", line 259, in send
    telegram_bot(title=title, content=content)
  File "/ql/scripts/notify.py", line 112, in telegram_bot
    response = requests.post(url=url, headers=headers, params=payload, proxies=proxies).json()
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botbot1234567890:xxxxxxx/sendMessage?chat_id=1234567&text=%E4%BA%AC%E4%B8%9C%E5%85%A8%E8%87%AA%E5%8A%A8%E8%AF%84%E4%BB%B7%0A%0A%E8%B4%A6%E5%8F%B71%5B%E9%85%92%E5%B7%B7joux%5D%0A%7B%27%E8%AF%84%E4%BB%B7%27%3A+0%2C+%27%E6%99%92%E5%8D%95%27%3A+0%2C+%27%E6%9C%8D%E5%8A%A1%E8%AF%84%E4%BB%B7%27%3A+1%7D%0A%0A&disable_web_page_preview=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6998bf2fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Ocyss** [comment]
这是推送脚本问题 我不知到。。












lzsnmb
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月7日(周日) 晚上6:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiu-lzsnmb/jd_lzsnmb] 通知好像有问题 (Issue #8)




 
tg服务启动
 Traceback (most recent call last):
 File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
 conn = connection.create_connection(
 File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
 raise err
 File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
 sock.connect(sa)
 ConnectionRefusedError: [Errno 111] Connection refused
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
 httplib_response = self._make_request(
 File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
 self._validate_conn(conn)
 File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
 conn.connect()
 File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
 conn = self._new_conn()
 File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
 raise NewConnectionError(
 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6998bf2fa0&gt;: Failed to establish a new connection: [Errno 111] Connection refused
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
 resp = conn.urlopen(
 File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
 retries = retries.increment(
 File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
 raise MaxRetryError(_pool, url, error or ResponseError(cause))
 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1234567890:xxxxxxx/sendMessage?chat_id=1234567890&amp;text=%E4%BA%AC%E4%B8%9C%E5%85%A8%E8%87%AA%E5%8A%A8%E8%AF%84%E4%BB%B7%0A%0A%E8%B4%A6%E5%8F%B71%5B%E9%85%92%E5%B7%B7joux%5D%0A%7B%27%E8%AF%84%E4%BB%B7%27%3A+0%2C+%27%E6%99%92%E5%8D%95%27%3A+0%2C+%27%E6%9C%8D%E5%8A%A1%E8%AF%84%E4%BB%B7%27%3A+1%7D%0A%0A&amp;disable_web_page_preview=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6998bf2fa0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "raw_jd_Evaluation.py", line 513, in 
 start()
 File "raw_jd_Evaluation.py", line 509, in start
 send('京东全自动评价', msg)
 File "/ql/scripts/notify.py", line 259, in send
 telegram_bot(title=title, content=content)
 File "/ql/scripts/notify.py", line 112, in telegram_bot
 response = requests.post(url=url, headers=headers, params=payload, proxies=proxies).json()
 File "/usr/lib/python3.8/site-packages/requests/api.py", line 119, in post
 return request('post', url, data=data, json=json, **kwargs)
 File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
 return session.request(method=method, url=url, **kwargs)
 File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
 resp = self.send(prep, **send_kwargs)
 File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
 r = adapter.send(request, **kwargs)
 File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
 raise ConnectionError(e, request=request)
 requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botbot1234567890:xxxxxxx/sendMessage?chat_id=1234567&amp;text=%E4%BA%AC%E4%B8%9C%E5%85%A8%E8%87%AA%E5%8A%A8%E8%AF%84%E4%BB%B7%0A%0A%E8%B4%A6%E5%8F%B71%5B%E9%85%92%E5%B7%B7joux%5D%0A%7B%27%E8%AF%84%E4%BB%B7%27%3A+0%2C+%27%E6%99%92%E5%8D%95%27%3A+0%2C+%27%E6%9C%8D%E5%8A%A1%E8%AF%84%E4%BB%B7%27%3A+1%7D%0A%0A&amp;disable_web_page_preview=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6998bf2fa0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
